project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_ACCESS_TOKEN
preserve_hierarchy: 1
commit_message: Translation
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
