project_id_env: CROWDIN_PROJECT
api_token_env: CROWDIN_ACCESS_TOKEN
preserve_hierarchy: true
commit_message: "Translation"
files:
  ### JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  ### Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
  ## Blog Markdown files
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/current/**/%original_file_name%