name: "Crowdin Upload"

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crowdin/github-action@1.4.12
        with:
          upload_sources: true
          upload_translations: false
          import_eq_suggestions: true
          download_translations: false