name: "Crowdin Download"

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crowdin/github-action@1.4.12
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          github_user_name: AdwCustomizer
          github_user_email: AdwCustomizerTeam@proton.me